### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by UtentePierpaolo** [gatekeeper-project/gk-fhir-ig#12]
When cloning this repository and then running 'docker build -t gk-fhir-ig ./', I get the following error:

executor failed running [/bin/sh -c wget -q https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar &&     java -jar publisher.jar -ig .]: exit code: 1

Can you guess why? How can I fix it?
Many thanks

**Comment by gcangioli** [comment]
if you want to compile the guide my suggestion is to simply run the _genonce script after having launched the _updatePublisher one if the publisher has not been recently updated.
